---
version: 2
builds:
  - id: redirector
    main: ./cmd/redirector
    binary: redirector
    ldflags:
      - -s -w -X main.appVersion={{.Version}} -X main.buildTimestamp={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    goamd64: ["v1", "v2", "v3"]
    mod_timestamp: "{{ .CommitTimestamp }}"
  - id: migrator
    main: ./cmd/migrator
    binary: migrator
    ldflags:
      - -s -w -X main.appVersion={{.Version}} -X main.buildTimestamp={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    goamd64: ["v1", "v2", "v3"]
    mod_timestamp: "{{ .CommitTimestamp }}"
archives:
  - format: binary
checksum:
  name_template: "checksums.txt"
  algorithm: sha256
  split: false
  disable: false
release:
  prerelease: auto
  header: |
    ## linker {{ .Tag }} release

    Date: {{ .Date }}

